// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using soul_whisper.Data;

#nullable disable

namespace soul_whisper.Migrations
{
    [DbContext(typeof(FlatformContext))]
    partial class FlatformContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Achievement", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateEarned")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("doctorid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("modifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("doctorid");

                    b.ToTable("Achievement");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Achievement_Image", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("belongToid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("belongToid");

                    b.ToTable("Achievement_Image");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Admin", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("activationStatus")
                        .HasColumnType("int");

                    b.Property<DateOnly>("birthday")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Appointment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Patient_Doctor_Registrationid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("doctorid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("endTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("patientid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("prescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Patient_Doctor_Registrationid");

                    b.HasIndex("doctorid");

                    b.HasIndex("patientid");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Doctor", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("activationStatus")
                        .HasColumnType("int");

                    b.Property<string>("avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("birthday")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<decimal>("moneyInWallet")
                        .HasColumnType("Money");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("specialty")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("doctors");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Doctorship_Registration", b =>
                {
                    b.Property<Guid>("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("doctorship_registrations");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Exercise", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Doctorid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("duration")
                        .HasColumnType("TIME");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Doctorid");

                    b.ToTable("exercises");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Habit", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("patientid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("patientid");

                    b.ToTable("habits");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Message", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("receiver")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("sender")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Patient", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("activationStatus")
                        .HasColumnType("int");

                    b.Property<DateOnly>("birthday")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("patients");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Patient_Doctor_Registration", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("doctorid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("patientid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("doctorid");

                    b.HasIndex("patientid");

                    b.ToTable("patient_doctor_registrations");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Rating", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("doctorid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("patientid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("value")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("doctorid");

                    b.HasIndex("patientid");

                    b.ToTable("ratings");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Receipt", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("Money");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctorid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("patientid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("doctorid");

                    b.HasIndex("patientid");

                    b.ToTable("receipts");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Rule", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("rules");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Achievement", b =>
                {
                    b.HasOne("soul_whisper.Models.Private.Data.Doctor", "doctor")
                        .WithMany("achievements")
                        .HasForeignKey("doctorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("doctor");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Achievement_Image", b =>
                {
                    b.HasOne("soul_whisper.Models.Private.Data.Achievement", "belongTo")
                        .WithMany("image")
                        .HasForeignKey("belongToid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("belongTo");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Appointment", b =>
                {
                    b.HasOne("soul_whisper.Models.Private.Data.Patient_Doctor_Registration", null)
                        .WithMany("appointments")
                        .HasForeignKey("Patient_Doctor_Registrationid");

                    b.HasOne("soul_whisper.Models.Private.Data.Doctor", "doctor")
                        .WithMany("appointments")
                        .HasForeignKey("doctorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("soul_whisper.Models.Private.Data.Patient", "patient")
                        .WithMany("appointments")
                        .HasForeignKey("patientid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("doctor");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Doctorship_Registration", b =>
                {
                    b.HasOne("soul_whisper.Models.Private.Data.Doctor", "registrant")
                        .WithMany()
                        .HasForeignKey("id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("registrant");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Exercise", b =>
                {
                    b.HasOne("soul_whisper.Models.Private.Data.Doctor", null)
                        .WithMany("exercises")
                        .HasForeignKey("Doctorid");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Habit", b =>
                {
                    b.HasOne("soul_whisper.Models.Private.Data.Patient", "patient")
                        .WithMany("Habits")
                        .HasForeignKey("patientid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("patient");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Patient_Doctor_Registration", b =>
                {
                    b.HasOne("soul_whisper.Models.Private.Data.Doctor", "doctor")
                        .WithMany("patientDoctorRegistrations")
                        .HasForeignKey("doctorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("soul_whisper.Models.Private.Data.Patient", "patient")
                        .WithMany("registrations")
                        .HasForeignKey("patientid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("doctor");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Rating", b =>
                {
                    b.HasOne("soul_whisper.Models.Private.Data.Doctor", "doctor")
                        .WithMany("ratings")
                        .HasForeignKey("doctorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("soul_whisper.Models.Private.Data.Patient", "patient")
                        .WithMany("ratings")
                        .HasForeignKey("patientid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("doctor");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Receipt", b =>
                {
                    b.HasOne("soul_whisper.Models.Private.Data.Doctor", "doctor")
                        .WithMany("receipts")
                        .HasForeignKey("doctorid");

                    b.HasOne("soul_whisper.Models.Private.Data.Patient", "patient")
                        .WithMany("receipts")
                        .HasForeignKey("patientid");

                    b.Navigation("doctor");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Achievement", b =>
                {
                    b.Navigation("image");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Doctor", b =>
                {
                    b.Navigation("achievements");

                    b.Navigation("appointments");

                    b.Navigation("exercises");

                    b.Navigation("patientDoctorRegistrations");

                    b.Navigation("ratings");

                    b.Navigation("receipts");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Patient", b =>
                {
                    b.Navigation("Habits");

                    b.Navigation("appointments");

                    b.Navigation("ratings");

                    b.Navigation("receipts");

                    b.Navigation("registrations");
                });

            modelBuilder.Entity("soul_whisper.Models.Private.Data.Patient_Doctor_Registration", b =>
                {
                    b.Navigation("appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
